// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type DelegateTask struct {
	ID                 string
	IntentJson         string
	ForfeitTx          string
	InputsJson         string
	Fee                int64
	DelegatorPublicKey string
	ScheduledAt        int64
	Status             string
	FailReason         string
}

type Setting struct {
	ID          int64
	ApiRoot     string
	ServerUrl   string
	EsploraUrl  sql.NullString
	Currency    string
	EventServer string
	FullNode    string
	LnUrl       sql.NullString
	Unit        string
	LnDatadir   sql.NullString
	LnType      sql.NullInt64
}

type SubscribedScript struct {
	Script string
}

type Swap struct {
	ID           string
	Amount       int64
	Timestamp    int64
	ToCurrency   string
	FromCurrency string
	Status       int64
	SwapType     int64
	Invoice      string
	FundingTxID  string
	RedeemTxID   string
	VhtlcID      string
}

type Vhtlc struct {
	ID                                        string
	PreimageHash                              string
	Sender                                    string
	Receiver                                  string
	Server                                    string
	RefundLocktime                            int64
	UnilateralClaimDelayType                  int64
	UnilateralClaimDelayValue                 int64
	UnilateralRefundDelayType                 int64
	UnilateralRefundDelayValue                int64
	UnilateralRefundWithoutReceiverDelayType  int64
	UnilateralRefundWithoutReceiverDelayValue int64
}

type VtxoRollover struct {
	Address            string
	TaprootTree        string
	DestinationAddress string
}
