version: 2

builds:
  - id: ark-node
    main: ./cmd/ark-node
    binary: ark-node
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - formats: [binary]
    name_template: "ark-node_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

app_bundles:
  - bundle: com.arklabs.ark-node
    icon: ./static/myapp.icns
    if: '{{eq .Os "darwin"}}'

dmg:
  - name: ark-node
    use: appbundle

release:
  disable: true