// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// BodyContent defines HTML content.
func HomeBodyContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"py-12\">Welcome to Fulmine</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func PagesScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_PagesScript_7a43`,
		Function: `function __templ_PagesScript_7a43(){// from 4321 to 0.00004321 with '0' in gray
  const prettyBtc = (btc) => {
    if (!/\d/.test(btc)) return data // not a number
    const prefix = /^[\D]/.test(btc) ? btc[0] : ''
    const number = /^[\D]/.test(btc) ? btc.slice(1) : btc
	  const length = String(number).length
    if (length > 8) return number
    let padding = '0.'
    for (let i = length; i < 8; i++) padding += '0'
	  return ` + "`" + `${prefix}<span class="text-gray-400">${padding}</span>${number}` + "`" + `
  }
}`,
		Call:       templ.SafeScript(`__templ_PagesScript_7a43`),
		CallInline: templ.SafeScriptInline(`__templ_PagesScript_7a43`),
	}
}
