// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

// BodyScripts defines JavaScript code.
// Needs to be here in order for tailwind to detect class name.
func BodyScripts() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_BodyScripts_28b3`,
		Function: `function __templ_BodyScripts_28b3(){// from 4321 to 0.00004321 with '0' in gray
  const prettySats = (data) => {
    if (!/\d/.test(data)) return data // not a number
    const prefix = /^[\D]/.test(data) ? data[0] : ''
    const number = /^[\D]/.test(data) ? data.slice(1) : data
	  const length = String(number).length
    if (length > 8) return number
    let padding = '0.'
    for (let i = length; i < 8; i++) padding += '0'
	  return ` + "`" + `${prefix}<span class="text-gray-400">${padding}</span>${number}` + "`" + `
  }
    
  document.querySelectorAll('.sats').forEach((x) => {
	  x.innerHTML = prettySats(x.textContent)
  })
}`,
		Call:       templ.SafeScript(`__templ_BodyScripts_28b3`),
		CallInline: templ.SafeScriptInline(`__templ_BodyScripts_28b3`),
	}
}
