#!/bin/bash

set -e

PARENT_PATH=$(dirname $(
	cd $(dirname $0)
	pwd -P
))

# Use provided OS and ARCH if given, otherwise determine from environment
OS="${1:-$(go env GOOS)}"
ARCH="${2:-$(go env GOARCH)}"

pushd $PARENT_PATH
mkdir -p build
go build -ldflags="-s -w" -o build/ark-node-desktop-$OS-$ARCH cmd/ark-node/desktop/main.go
popd
