#!/bin/bash

set -e

PARENT_PATH=$(dirname $(
	cd $(dirname $0)
	pwd -P
))

OS=$(eval "go env GOOS")
ARCH=$(eval "go env GOARCH")

pushd $PARENT_PATH
mkdir -p build
go build -ldflags="-s -w" -o build/ark-node-$OS-$ARCH cmd/ark-node/headless/main.go
popd
